### ISSUE TITLE
Torba scraper

### ISSUE THREAD

**Issue by Kodi-4-Beginners** [tknorris/salts#154] opened 2016-02-22 08:15 UTC
Hi can you take a look @ the Torba scraper? Movies are down
To watch this movie please visit htttp://torba.se

And it looks like Alluc is down...

And is is it possible to add genres to movie section?

Thx keep up the good work!

Grz..

**Comment by tknorris** [comment] 2016-02-22 08:37
Torba works fine here
Alluc just needs a changed base url which is already done in the beta, and can be changed manually in the addon settings.
I won't be adding Genres as 1) I don't use them and 2) The trakt API doesn't provide them.

**Closed by tknorris** 2016-02-22 08:37 UTC

**Comment by Kodi-4-Beginners** [comment] 2016-02-22 09:12
Running 2.0.7 stil i get this massage: To watch this movie please visit htttp://torba.se
I am in Holland so maybe it's a regional thing?

**Comment by tknorris** [comment] 2016-02-22 15:43
I don't know I'll check again. Others have reported seeing the same message but I can't reproduce it.
